### ISSUE TITLE
You need to enable JavaScript to run this app

### ISSUE THREAD

**Issue by sjparkinson** [brittonjg/britton.app#2]
https://github.com/brittonjg/britton.app/blob/23f4be93e966cecc22c3472e3f06ec52db2f51c2/public/index.html#L32-L34

This makes me sad 😢.

**Comment by brittonjg** [comment]
Understood! That should be a consideration, now I need to find out how to implement that without creating split effort 🤔

**Comment by brittonjg** [comment]
![screenshot 2018-12-21 at 18 49 17](https://user-images.githubusercontent.com/12110204/50358423-29020980-0551-11e9-9a3a-805adee59145.png)

Must not look this ugly 😱

**Comment by sjparkinson** [comment]
> Do you know of any concepts/tools/resources that might be of assistance?

Here's some links from the way things are done at the FT.

* https://github.com/Financial-Times/ft-origami/issues/88
* https://origami.ft.com/docs/syntax/js/#browser-support

**Comment by sjparkinson** [comment]
And if you fancy learning more, https://ft.wd3.myworkdayjobs.com/en-US/FT_External_Careers/job/London-FT/Senior-Engineer_JR002452.

**Comment by brittonjg** [comment]
> > Do you know of any concepts/tools/resources that might be of assistance?
> 
> Here's some links from the way things are done at the FT.
> 
> * [Financial-Times/ft-origami#88](https://github.com/Financial-Times/ft-origami/issues/88)
> * https://origami.ft.com/docs/syntax/js/#browser-support

Thanks! I'll give these a look over. 

> And if you fancy learning more, https://ft.wd3.myworkdayjobs.com/en-US/FT_External_Careers/job/London-FT/Senior-Engineer_JR002452.

Ha! I might just do that 😅

Is that page meant to download a blank file automatically @sjparkinson? 🤔

**Comment by sjparkinson** [comment]
Baha, no. It too could do with less javascript 🤦‍♀️.

Alternative is https://roles.ft.com/openings.html.

**Comment by kirhov** [comment]
I am having the <noscript>You need to enable JavaScript to run this app.</noscript> issue. I am attempting to clone a website, downloaded the website to my computer and tried changing text in the html file, but when I open html in my browser the changes are displayed for a fraction of a sec or when its loading the page and then comes back to the original setting and when I inspect I see this <noscript>You need to enable JavaScript to run this app.</noscript> error, Javascript is turned on in browser. Any idea what can I try?
